### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by tomonsoejang** [vigneshm-quikieapps/risign-stars-backend#31]
## Business Other Infomation
- [x]  add social media handles of the business (e.g URL of the Facebook page, Instagram page, Pinterest page, LinkedIn page)

## club membership id
- [x] generate a unique club membership id for a member when enrolling in a club
- [x] This id should be unique for a member of a particular club
- [x] If a member enrolls in multiple clubs, he will have a unique id for each club.
- [x] Club id will be in the following format: `BUSINESS CODE` + `Year of enrollment` + `4 digits serial number (starting from 1001 to 9999)`

**Comment by sudarshanshkrishna** [comment]
marked things are complete
