### ISSUE TITLE
Class Definition API

### ISSUE THREAD

**Issue by tomonsoejang** [vigneshm-quikieapps/risign-stars-backend#9]
## Todo
- [x] listing classes 
- [x] create class
- [x] read/get a particular class
- [x] update class
- [x] delete class
- [x] restrict deletion of class, if it has sessions.

**Comment by sudarshanshkrishna** [comment]
completed above 5 tasks

**Comment by sudarshanshkrishna** [comment]
completed below regarding above tasks

**Comment by sudarshanshkrishna** [comment]
completed below regarding assigned tasks
1. created schemas for al above tasks.
2. created api's for all above assigned tasks.
3. written complete validations/custom validations for above tasks.
4. tested all api's /validations / validation error messages

Summary:- completed all assigned tasks.
